/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as UsernameIndexRouteImport } from './routes/$username.index'
import { Route as UsernameSlugRouteImport } from './routes/$username.$slug'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedAvailabilityRouteImport } from './routes/_authenticated/availability'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEventTypesRouteImport } from './routes/_authenticated/event-types'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AiTokenRouteImport } from './routes/ai/$token'
import { Route as ApiBookingsRouteImport } from './routes/api/bookings'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as BookingTokenRouteImport } from './routes/booking.$token'
import { Route as ApiBookingTokenRouteImport } from './routes/api/booking/$token'
import { Route as ApiBookingsIdRouteImport } from './routes/api/bookings/$id'
import { Route as ApiBookingsCancelRouteImport } from './routes/api/bookings/cancel'
import { Route as ApiBookingsRescheduleRouteImport } from './routes/api/bookings/reschedule'
import { Route as ApiRemindersCancelRouteImport } from './routes/api/reminders/cancel'
import { Route as ApiRemindersCreateRouteImport } from './routes/api/reminders/create'
import { Route as ApiOauthGoogleCallbackRouteImport } from './routes/api/oauth/google/callback'
import { Route as ApiPublicHooksInboundEmailRouteImport } from './routes/api/public/hooks/inbound-email'
import { Route as ApiPublicHooksRemindersRouteImport } from './routes/api/public/hooks/reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameIndexRoute = UsernameIndexRouteImport.update({
  id: '/$username/',
  path: '/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameSlugRoute = UsernameSlugRouteImport.update({
  id: '/$username/$slug',
  path: '/$username/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAvailabilityRoute =
  AuthenticatedAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventTypesRoute = AuthenticatedEventTypesRouteImport.update({
  id: '/event-types',
  path: '/event-types',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AiTokenRoute = AiTokenRouteImport.update({
  id: '/ai/$token',
  path: '/ai/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsRoute = ApiBookingsRouteImport.update({
  id: '/api/bookings',
  path: '/api/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const BookingTokenRoute = BookingTokenRouteImport.update({
  id: '/booking/$token',
  path: '/booking/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingTokenRoute = ApiBookingTokenRouteImport.update({
  id: '/api/booking/$token',
  path: '/api/booking/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsIdRoute = ApiBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiBookingsRoute,
} as any)
const ApiBookingsCancelRoute = ApiBookingsCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => ApiBookingsRoute,
} as any)
const ApiBookingsRescheduleRoute = ApiBookingsRescheduleRouteImport.update({
  id: '/reschedule',
  path: '/reschedule',
  getParentRoute: () => ApiBookingsRoute,
} as any)
const ApiRemindersCancelRoute = ApiRemindersCancelRouteImport.update({
  id: '/api/reminders/cancel',
  path: '/api/reminders/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemindersCreateRoute = ApiRemindersCreateRouteImport.update({
  id: '/api/reminders/create',
  path: '/api/reminders/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthGoogleCallbackRoute = ApiOauthGoogleCallbackRouteImport.update({
  id: '/api/oauth/google/callback',
  path: '/api/oauth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksInboundEmailRoute =
  ApiPublicHooksInboundEmailRouteImport.update({
    id: '/api/public/hooks/inbound-email',
    path: '/api/public/hooks/inbound-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRemindersRoute = ApiPublicHooksRemindersRouteImport.update({
  id: '/api/public/hooks/reminders',
  path: '/api/public/hooks/reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/$username/$slug': typeof UsernameSlugRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/event-types': typeof AuthenticatedEventTypesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/ai/$token': typeof AiTokenRoute
  '/api/bookings': typeof ApiBookingsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/booking/$token': typeof BookingTokenRoute
  '/$username/': typeof UsernameIndexRoute
  '/api/booking/$token': typeof ApiBookingTokenRoute
  '/api/bookings/$id': typeof ApiBookingsIdRoute
  '/api/bookings/cancel': typeof ApiBookingsCancelRoute
  '/api/bookings/reschedule': typeof ApiBookingsRescheduleRoute
  '/api/reminders/cancel': typeof ApiRemindersCancelRoute
  '/api/reminders/create': typeof ApiRemindersCreateRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/public/hooks/inbound-email': typeof ApiPublicHooksInboundEmailRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/$username/$slug': typeof UsernameSlugRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/event-types': typeof AuthenticatedEventTypesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/ai/$token': typeof AiTokenRoute
  '/api/bookings': typeof ApiBookingsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/booking/$token': typeof BookingTokenRoute
  '/$username': typeof UsernameIndexRoute
  '/api/booking/$token': typeof ApiBookingTokenRoute
  '/api/bookings/$id': typeof ApiBookingsIdRoute
  '/api/bookings/cancel': typeof ApiBookingsCancelRoute
  '/api/bookings/reschedule': typeof ApiBookingsRescheduleRoute
  '/api/reminders/cancel': typeof ApiRemindersCancelRoute
  '/api/reminders/create': typeof ApiRemindersCreateRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/public/hooks/inbound-email': typeof ApiPublicHooksInboundEmailRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/$username/$slug': typeof UsernameSlugRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRoute
  '/_authenticated/availability': typeof AuthenticatedAvailabilityRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/event-types': typeof AuthenticatedEventTypesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/ai/$token': typeof AiTokenRoute
  '/api/bookings': typeof ApiBookingsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/booking/$token': typeof BookingTokenRoute
  '/$username/': typeof UsernameIndexRoute
  '/api/booking/$token': typeof ApiBookingTokenRoute
  '/api/bookings/$id': typeof ApiBookingsIdRoute
  '/api/bookings/cancel': typeof ApiBookingsCancelRoute
  '/api/bookings/reschedule': typeof ApiBookingsRescheduleRoute
  '/api/reminders/cancel': typeof ApiRemindersCancelRoute
  '/api/reminders/create': typeof ApiRemindersCreateRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/public/hooks/inbound-email': typeof ApiPublicHooksInboundEmailRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/$username/$slug'
    | '/automations'
    | '/availability'
    | '/contacts'
    | '/dashboard'
    | '/event-types'
    | '/settings'
    | '/ai/$token'
    | '/api/bookings'
    | '/auth/callback'
    | '/booking/$token'
    | '/$username/'
    | '/api/booking/$token'
    | '/api/bookings/$id'
    | '/api/bookings/cancel'
    | '/api/bookings/reschedule'
    | '/api/reminders/cancel'
    | '/api/reminders/create'
    | '/api/oauth/google/callback'
    | '/api/public/hooks/inbound-email'
    | '/api/public/hooks/reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/$username/$slug'
    | '/automations'
    | '/availability'
    | '/contacts'
    | '/dashboard'
    | '/event-types'
    | '/settings'
    | '/ai/$token'
    | '/api/bookings'
    | '/auth/callback'
    | '/booking/$token'
    | '/$username'
    | '/api/booking/$token'
    | '/api/bookings/$id'
    | '/api/bookings/cancel'
    | '/api/bookings/reschedule'
    | '/api/reminders/cancel'
    | '/api/reminders/create'
    | '/api/oauth/google/callback'
    | '/api/public/hooks/inbound-email'
    | '/api/public/hooks/reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/calendar'
    | '/$username/$slug'
    | '/_authenticated/automations'
    | '/_authenticated/availability'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/event-types'
    | '/_authenticated/settings'
    | '/ai/$token'
    | '/api/bookings'
    | '/auth/callback'
    | '/booking/$token'
    | '/$username/'
    | '/api/booking/$token'
    | '/api/bookings/$id'
    | '/api/bookings/cancel'
    | '/api/bookings/reschedule'
    | '/api/reminders/cancel'
    | '/api/reminders/create'
    | '/api/oauth/google/callback'
    | '/api/public/hooks/inbound-email'
    | '/api/public/hooks/reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  UsernameSlugRoute: typeof UsernameSlugRoute
  AiTokenRoute: typeof AiTokenRoute
  ApiBookingsRoute: typeof ApiBookingsRouteWithChildren
  BookingTokenRoute: typeof BookingTokenRoute
  UsernameIndexRoute: typeof UsernameIndexRoute
  ApiBookingTokenRoute: typeof ApiBookingTokenRoute
  ApiRemindersCancelRoute: typeof ApiRemindersCancelRoute
  ApiRemindersCreateRoute: typeof ApiRemindersCreateRoute
  ApiOauthGoogleCallbackRoute: typeof ApiOauthGoogleCallbackRoute
  ApiPublicHooksInboundEmailRoute: typeof ApiPublicHooksInboundEmailRoute
  ApiPublicHooksRemindersRoute: typeof ApiPublicHooksRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/': {
      id: '/$username/'
      path: '/$username'
      fullPath: '/$username/'
      preLoaderRoute: typeof UsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$slug': {
      id: '/$username/$slug'
      path: '/$username/$slug'
      fullPath: '/$username/$slug'
      preLoaderRoute: typeof UsernameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/availability': {
      id: '/_authenticated/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AuthenticatedAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/event-types': {
      id: '/_authenticated/event-types'
      path: '/event-types'
      fullPath: '/event-types'
      preLoaderRoute: typeof AuthenticatedEventTypesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/ai/$token': {
      id: '/ai/$token'
      path: '/ai/$token'
      fullPath: '/ai/$token'
      preLoaderRoute: typeof AiTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings': {
      id: '/api/bookings'
      path: '/api/bookings'
      fullPath: '/api/bookings'
      preLoaderRoute: typeof ApiBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/booking/$token': {
      id: '/booking/$token'
      path: '/booking/$token'
      fullPath: '/booking/$token'
      preLoaderRoute: typeof BookingTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking/$token': {
      id: '/api/booking/$token'
      path: '/api/booking/$token'
      fullPath: '/api/booking/$token'
      preLoaderRoute: typeof ApiBookingTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings/$id': {
      id: '/api/bookings/$id'
      path: '/$id'
      fullPath: '/api/bookings/$id'
      preLoaderRoute: typeof ApiBookingsIdRouteImport
      parentRoute: typeof ApiBookingsRoute
    }
    '/api/bookings/cancel': {
      id: '/api/bookings/cancel'
      path: '/cancel'
      fullPath: '/api/bookings/cancel'
      preLoaderRoute: typeof ApiBookingsCancelRouteImport
      parentRoute: typeof ApiBookingsRoute
    }
    '/api/bookings/reschedule': {
      id: '/api/bookings/reschedule'
      path: '/reschedule'
      fullPath: '/api/bookings/reschedule'
      preLoaderRoute: typeof ApiBookingsRescheduleRouteImport
      parentRoute: typeof ApiBookingsRoute
    }
    '/api/reminders/cancel': {
      id: '/api/reminders/cancel'
      path: '/api/reminders/cancel'
      fullPath: '/api/reminders/cancel'
      preLoaderRoute: typeof ApiRemindersCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reminders/create': {
      id: '/api/reminders/create'
      path: '/api/reminders/create'
      fullPath: '/api/reminders/create'
      preLoaderRoute: typeof ApiRemindersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/google/callback': {
      id: '/api/oauth/google/callback'
      path: '/api/oauth/google/callback'
      fullPath: '/api/oauth/google/callback'
      preLoaderRoute: typeof ApiOauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/inbound-email': {
      id: '/api/public/hooks/inbound-email'
      path: '/api/public/hooks/inbound-email'
      fullPath: '/api/public/hooks/inbound-email'
      preLoaderRoute: typeof ApiPublicHooksInboundEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reminders': {
      id: '/api/public/hooks/reminders'
      path: '/api/public/hooks/reminders'
      fullPath: '/api/public/hooks/reminders'
      preLoaderRoute: typeof ApiPublicHooksRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRoute
  AuthenticatedAvailabilityRoute: typeof AuthenticatedAvailabilityRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEventTypesRoute: typeof AuthenticatedEventTypesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRoute,
  AuthenticatedAvailabilityRoute: AuthenticatedAvailabilityRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEventTypesRoute: AuthenticatedEventTypesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ApiBookingsRouteChildren {
  ApiBookingsIdRoute: typeof ApiBookingsIdRoute
  ApiBookingsCancelRoute: typeof ApiBookingsCancelRoute
  ApiBookingsRescheduleRoute: typeof ApiBookingsRescheduleRoute
}

const ApiBookingsRouteChildren: ApiBookingsRouteChildren = {
  ApiBookingsIdRoute: ApiBookingsIdRoute,
  ApiBookingsCancelRoute: ApiBookingsCancelRoute,
  ApiBookingsRescheduleRoute: ApiBookingsRescheduleRoute,
}

const ApiBookingsRouteWithChildren = ApiBookingsRoute._addFileChildren(
  ApiBookingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CalendarRoute: CalendarRoute,
  UsernameSlugRoute: UsernameSlugRoute,
  AiTokenRoute: AiTokenRoute,
  ApiBookingsRoute: ApiBookingsRouteWithChildren,
  BookingTokenRoute: BookingTokenRoute,
  UsernameIndexRoute: UsernameIndexRoute,
  ApiBookingTokenRoute: ApiBookingTokenRoute,
  ApiRemindersCancelRoute: ApiRemindersCancelRoute,
  ApiRemindersCreateRoute: ApiRemindersCreateRoute,
  ApiOauthGoogleCallbackRoute: ApiOauthGoogleCallbackRoute,
  ApiPublicHooksInboundEmailRoute: ApiPublicHooksInboundEmailRoute,
  ApiPublicHooksRemindersRoute: ApiPublicHooksRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
